import datetime
print(datetime.datetime.now())#prints actual date
print(datetime.datetime(2026,7,5,10,30,45,123))#prints date and time using constructor
t=datetime.datetime.now()
c=t.strftime("%y")
print("short version of year:",c)
c=t.strftime("%Y")
print("full version of year:",c)
c=t.strftime("%b")
print("short version of month:",c)
c=t.strftime("%B")
print("full version of month",c)
c=t.strftime("%a")
print("short version of day:",c)
c=t.strftime("%A")
print("full version of day:",c)
c=t.strftime("%w")
print("number of weekday:",c)
c=t.strftime("%H")
print("24 hours format:",c)
c=t.strftime("%M")
print("minutes:",c)
c=t.strftime("%S")
print("seconds:",c)
c=t.strftime("%p")
print("am/pm:",c)